# Fetching Census Survey Data

morpc-census connects to the US Census Bureau API, retrieves survey data, and returns it as a normalized long-format DataFrame ready for analysis. Every request is defined by:

- an **Endpoint** — survey dataset and vintage year
- a **scope** — geographic extent (a region, county, state, etc.)
- a **Group** or a list of **variables** — what to retrieve
- an optional **sumlevel** — resolution within the scope (county, tract, place, etc.)

This notebook walks through a typical workflow from discovery to analysis to saving output.

In [1]:
from morpc.logs import config_logs

config_logs('morpc-census-demo.log', 'debug')

2026-05-12 10:58:46,838 | INFO | morpc.logs.config_logs: Set up logging save to file "morpc-census-demo.log", log level "debug"

In [2]:
from morpc_census import (
    Endpoint, Group, CensusAPI, DimensionTable,
    get_all_avail_endpoints,
    IMPLEMENTED_ENDPOINTS, SCOPES,
)
import pandas as pd

## 1. Endpoints — choosing a survey and year

`IMPLEMENTED_ENDPOINTS` lists every survey/table the package supports. `Endpoint` validates the survey name and vintage year at construction time, so you find out immediately if you've specified something unavailable.

In [3]:
# Surveys the package supports
IMPLEMENTED_ENDPOINTS

['acs/acs1',
 'acs/acs1/profile',
 'acs/acs1/subject',
 'acs/acs5',
 'acs/acs5/profile',
 'acs/acs5/subject',
 'dec/pl',
 'dec/dhc',
 'dec/ddhca',
 'dec/ddhcb',
 'dec/sf1',
 'dec/sf2',
 'dec/sf3',
 'geoinfo']

In [4]:
# Construct an endpoint — raises ValueError for unknown surveys or unavailable years
ep = Endpoint('acs/acs5', 2023)
ep

2026-05-12 10:58:51,990 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data with parameters {'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:58:51,996 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:58:52,210 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 302 None
2026-05-12 10:58:52,281 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 10:58:54,968 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.

Endpoint('acs/acs5', 2023)

In [5]:
# All vintage years available for this survey
ep.vintages

[2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024]

## 2. Groups — browsing available variables

> **Network required** — the cells below make live calls to the Census API.

A *group* is a table within a survey — a collection of related variables. `endpoint.groups` returns every group with its description. Fetched once, then cached on the object.

In [6]:
# Browse available groups — descriptions keyed by group code
{k: v['description'] for k, v in list(ep.groups.items())[:10]}

2026-05-12 10:59:02,357 | DEBUG | morpc_census.api.groups: Fetching groups for 2023 acs/acs5
2026-05-12 10:59:02,359 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups.json with parameters {'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:59:02,361 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:02,589 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups.json?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 10:59:02,973 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.

{'B01001': 'Sex by Age',
 'B01001A': 'Sex by Age (White Alone)',
 'B01001B': 'Sex by Age (Black or African American Alone)',
 'B01001C': 'Sex by Age (American Indian and Alaska Native Alone)',
 'B01001D': 'Sex by Age (Asian Alone)',
 'B01001E': 'Sex by Age (Native Hawaiian and Other Pacific Islander Alone)',
 'B01001F': 'Sex by Age (Some Other Race Alone)',
 'B01001G': 'Sex by Age (Two or More Races)',
 'B01001H': 'Sex by Age (White Alone, Not Hispanic or Latino)',
 'B01001I': 'Sex by Age (Hispanic or Latino)'}

In [7]:
# Construct a Group — validates the code against endpoint.groups
group = Group(ep, 'B01001')
print(group.description)
print(group.universe)

Sex by Age
Total population

In [8]:
# Variable codes and labels for this group
{k: v.get('label', '') for k, v in list(group.variables.items())[:8]}

2026-05-12 10:59:05,520 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups/B01001.json with parameters {'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:59:05,523 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:05,738 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups/B01001.json?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 19404
2026-05-12 10:59:05,771 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.

{'B01001_001E': 'Estimate!!Total:',
 'B01001_001EA': 'Annotation of Estimate!!Total:',
 'B01001_001M': 'Margin of Error!!Total:',
 'B01001_001MA': 'Annotation of Margin of Error!!Total:',
 'B01001_002E': 'Estimate!!Total:!!Male:',
 'B01001_002EA': 'Annotation of Estimate!!Total:!!Male:',
 'B01001_002M': 'Margin of Error!!Total:!!Male:',
 'B01001_002MA': 'Annotation of Margin of Error!!Total:!!Male:'}

## 3. Scopes — choosing a geographic extent

A scope names the geographic coverage of the request — which places to include. `SCOPES` lists all built-in scopes. Pass a scope key to `CensusAPI` as a string.

In [9]:
# Available scope keys
list(SCOPES.keys())

['us',
 'columbuscbsa',
 'alabama',
 'alaska',
 'arizona',
 'arkansas',
 'california',
 'colorado',
 'connecticut',
 'delaware',
 'district of columbia',
 'florida',
 'georgia',
 'hawaii',
 'idaho',
 'illinois',
 'indiana',
 'iowa',
 'kansas',
 'kentucky',
 'louisiana',
 'maine',
 'maryland',
 'massachusetts',
 'michigan',
 'minnesota',
 'mississippi',
 'missouri',
 'montana',
 'nebraska',
 'nevada',
 'new hampshire',
 'new jersey',
 'new mexico',
 'new york',
 'north carolina',
 'north dakota',
 'ohio',
 'oklahoma',
 'oregon',
 'pennsylvania',
 'rhode island',
 'south carolina',
 'south dakota',
 'tennessee',
 'texas',
 'utah',
 'vermont',
 'virginia',
 'washington',
 'west virginia',
 'wisconsin',
 'wyoming',
 'puerto rico',
 'lake',
 'hancock',
 'allen',
 'morgan',
 'portage',
 'butler',
 'fayette',
 'vinton',
 'paulding',
 'scioto',
 'fulton',
 'henry',
 'logan',
 'brown',
 'monroe',
 'trumbull',
 'pike',
 'pickaway',
 'muskingum',
 'lawrence',
 'adams',
 'crawford',
 'guernsey',
 'van wert',
 'ottawa',
 'harrison',
 'richland',
 'champaign',
 'wayne',
 'clark',
 'hocking',
 'miami',
 'darke',
 'lucas',
 'ashtabula',
 'preble',
 'jackson',
 'stark',
 'greene',
 'ashland',
 'mahoning',
 'tuscarawas',
 'highland',
 'carroll',
 'belmont',
 'meigs',
 'medina',
 'gallia',
 'coshocton',
 'huron',
 'wood',
 'franklin',
 'seneca',
 'williams',
 'union',
 'cuyahoga',
 'summit',
 'warren',
 'madison',
 'geauga',
 'fairfield',
 'hardin',
 'hamilton',
 'knox',
 'shelby',
 'clermont',
 'noble',
 'putnam',
 'holmes',
 'columbiana',
 'licking',
 'ross',
 'montgomery',
 'marion',
 'perry',
 'defiance',
 'erie',
 'auglaize',
 'athens',
 'jefferson',
 'morrow',
 'clinton',
 'lorain',
 'sandusky',
 'wyandot',
 'mercer',
 'region15',
 'region10',
 'region7',
 'regioncorpo',
 'regionceds',
 'regioncbsa',
 'regionmobility',
 'regionmpo']

## 4. Fetching data

`CensusAPI` validates parameters, builds the request, fetches the data, and transforms it into a normalized long-format table in one step. `api.data` holds the raw wide response from the API; `api.long` is the normalized output.

In [10]:
# Sex by age for all counties in the 15-county MORPC region
b01001 = CensusAPI(ep, 'region15', group='b01001')
b01001.data

2026-05-12 10:59:12,855 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001.__init__: Initializing CensusAPI for census-acs-acs5-2023-region15-b01001.
2026-05-12 10:59:12,856 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001.__init__: Building request URL and parameters.
2026-05-12 10:59:12,858 | DEBUG | morpc_census.geos.geoids_from_scope: Fetching geoids from scope 'region15'.
2026-05-12 10:59:12,860 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/geoinfo?get=GEO_ID with parameters {'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141', 'in': 'state:39', 'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:59:12,862 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:13,311 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/geoinfo?get=GEO_ID&for=county%3A041%2C045%2C049%2C089%2C097%2C129%2C159%2C083%2C101%2C117%2C047%2C073%2C091%2C127%2C141&in=state%3A39&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 10:59:13,313 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-05-12 10:59:13,317 | DEBUG | morpc_census.geos.geoinfo_from_scope_sumlevel: Building parameters for scope 'region15' at sumlevel None.
2026-05-12 10:59:13,318 | INFO | morpc_census.geos.geoinfo_from_scope_sumlevel: No sumlevel specified; using scope 'region15' parameters.
2026-05-12 10:59:13,319 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001.__init__: Fetching data from https://api.census.gov/data/2023/acs/acs5? with params {'get': 'group(B01001)', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141', 'in': 'state:39'}.
2026-05-12 10:59:13,321 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001._fetch_group: Fetching group(B01001) — all variables, no limit.
2026-05-12 10:59:13,322 | DEBUG | morpc.req.get_text_safely: Getting data from https://api.census.gov/data/2023/acs/acs5?get=group(B01001)&for=county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141&in=state:39&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 with parameters None.
2026-05-12 10:59:13,326 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:13,843 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5?get=group(B01001)&for=county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141&in=state:39&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 10:59:13,876 | DEBUG | morpc.req.get_text_safely: Request successful. Returning plain text.
2026-05-12 10:59:13,917 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001.melt: Melting data to long format.
2026-05-12 10:59:13,938 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups/B01001.json with parameters {'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:59:13,940 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:14,138 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups/B01001.json?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 19404
2026-05-12 10:59:14,170 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.

,B01001_001E,B01001_001EA,B01001_001M,B01001_001MA,B01001_002E,B01001_002EA,B01001_002M,B01001_002MA,B01001_003E,B01001_003EA,...,B01001_048M,B01001_048MA,B01001_049E,B01001_049EA,B01001_049M,B01001_049MA,GEO_ID,NAME,state,county
0,221160,NaN,-555555555,*****,110668,NaN,33,NaN,6456,NaN,...,290,NaN,2009,NaN,352,NaN,0500000US39041,"Delaware County, Ohio",39,41
1,161289,NaN,-555555555,*****,80584,NaN,128,NaN,4690,NaN,...,241,NaN,1892,NaN,225,NaN,0500000US39045,"Fairfield County, Ohio",39,45
2,28880,NaN,-555555555,*****,14271,NaN,163,NaN,778,NaN,...,106,NaN,352,NaN,91,NaN,0500000US39047,"Fayette County, Ohio",39,47
3,1321635,NaN,-555555555,*****,649003,NaN,61,NaN,44950,NaN,...,692,NaN,11174,NaN,747,NaN,0500000US39049,"Franklin County, Ohio",39,49
4,27938,NaN,-555555555,*****,14022,NaN,110,NaN,808,NaN,...,102,NaN,248,NaN,87,NaN,0500000US39073,"Hocking County, Ohio",39,73
5,62888,NaN,-555555555,*****,31021,NaN,150,NaN,1943,NaN,...,175,NaN,895,NaN,160,NaN,0500000US39083,"Knox County, Ohio",39,83
6,180311,NaN,-555555555,*****,89196,NaN,116,NaN,5355,NaN,...,266,NaN,2124,NaN,256,NaN,0500000US39089,"Licking County, Ohio",39,89
7,46140,NaN,-555555555,*****,23206,NaN,100,NaN,1435,NaN,...,158,NaN,464,NaN,107,NaN,0500000US39091,"Logan County, Ohio",39,91
8,44126,NaN,-555555555,*****,24262,NaN,160,NaN,1181,NaN,...,126,NaN,525,NaN,130,NaN,0500000US39097,"Madison County, Ohio",39,97
9,65145,NaN,-555555555,*****,35012,NaN,168,NaN,1943,NaN,...,185,NaN,772,NaN,158,NaN,0500000US39101,"Marion County, Ohio",39,101
10,35214,NaN,-555555555,*****,17792,NaN,87,NaN,985,NaN,...,137,NaN,294,NaN,107,NaN,0500000US39117,"Morrow County, Ohio",39,117
11,35474,NaN,-555555555,*****,17781,NaN,82,NaN,1045,NaN,...,106,NaN,295,NaN,71,NaN,0500000US39127,"Perry County, Ohio",39,127
12,59407,NaN,-555555555,*****,31203,NaN,136,NaN,1612,NaN,...,167,NaN,500,NaN,112,NaN,0500000US39129,"Pickaway County, Ohio",39,129
13,76748,NaN,-555555555,*****,40007,NaN,190,NaN,2156,NaN,...,167,NaN,789,NaN,167,NaN,0500000US39141,"Ross County, Ohio",39,141
14,65293,NaN,-555555555,*****,31579,NaN,124,NaN,2028,NaN,...,129,NaN,522,NaN,148,NaN,0500000US39159,"Union County, Ohio",39,159

## 5. The long-format result

`api.long` is the normalized output: one row per geography × variable. Type suffixes are split into separate columns (`estimate`, `moe`), variable labels are extracted from the raw label strings, and Census missing-value codes are converted to `NaN`.

In [11]:
# Long-format output — one row per geography × variable
b01001.long

,geoidfq,name,reference_period,survey,concept,universe,variable_label,variable,estimate,moe
0,0500000US39041,"Delaware County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:,B01001_001,221160,-555555555
25,0500000US39041,"Delaware County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:!!Male:,B01001_002,110668,33
48,0500000US39041,"Delaware County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:!!Male:!!Under 5 years,B01001_003,6456,6
37,0500000US39041,"Delaware County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:!!Male:!!5 to 9 years,B01001_004,7560,466
26,0500000US39041,"Delaware County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:!!Male:!!10 to 14 years,B01001_005,9200,465
...,...,...,...,...,...,...,...,...,...,...
705,0500000US39159,"Union County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:!!Female:!!67 to 69 years,B01001_045,914,183
706,0500000US39159,"Union County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:!!Female:!!70 to 74 years,B01001_046,1201,211
707,0500000US39159,"Union County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:!!Female:!!75 to 79 years,B01001_047,738,161
708,0500000US39159,"Union County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:!!Female:!!80 to 84 years,B01001_048,571,129
709,0500000US39159,"Union County, Ohio",2023,acs/acs5,Sex by age,Total population,Total:!!Female:!!85 years and over,B01001_049,522,148

In [12]:
# Column types in the long-format output
b01001.long.dtypes

geoidfq             object
name                object
reference_period     int64
survey              object
concept             object
universe            object
variable_label      object
variable            object
estimate             int64
moe                  int64
dtype: object

## 6. GEOIDFQs — parsing geography identifiers

The `GEOIDFQ` column holds fully-qualified geography identifiers (e.g. `0500000US39049`). `api.geoidfqs` parses each one into a `GeoIDFQ` object with typed fields for summary level, variant, and component codes.

In [13]:
# First three geography IDs parsed as GeoIDFQ objects
b01001.geoidfqs[:3]

[GeoIDFQ(sumlevel='050', variant='00', geocomp='00', state='39', county='041'),
 GeoIDFQ(sumlevel='050', variant='00', geocomp='00', state='39', county='045'),
 GeoIDFQ(sumlevel='050', variant='00', geocomp='00', state='39', county='047')]

In [14]:
# Fields on a GeoIDFQ object
g = b01001.geoidfqs[0]
print('summary level:', g.sumlevel)
print('geoid:        ', g.geoid)
print('parts:        ', g.parts)
print('string form:  ', str(g))

summary level: '050'
geoid:         39041
parts:         {'state': '39', 'county': '041'}
string form:   0500000US39041

## 7. Drilling down with sumlevel

The `sumlevel` parameter fetches child geographies within the scope. For example, `sumlevel='tract'` with `scope='franklin'` returns all census tracts in Franklin County.

In [15]:
# Place of birth for all tracts in Franklin County
b05006_tracts = CensusAPI(ep, 'franklin', group='B05006', sumlevel='tract')
b05006_tracts.long

2026-05-12 10:59:26,158 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-countytract-franklin-b05006.__init__: Initializing CensusAPI for census-acs-acs5-2023-countytract-franklin-b05006.
2026-05-12 10:59:26,160 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-countytract-franklin-b05006.__init__: Building request URL and parameters.
2026-05-12 10:59:26,161 | DEBUG | morpc_census.geos.geoids_from_scope: Fetching geoids from scope 'franklin'.
2026-05-12 10:59:26,163 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/geoinfo?get=GEO_ID with parameters {'for': 'county:049', 'in': 'state:39', 'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:59:26,166 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:26,623 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/geoinfo?get=GEO_ID&for=county%3A049&in=state%3A39&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 10:59:26,626 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-05-12 10:59:26,630 | DEBUG | morpc_census.geos.geoinfo_from_scope_sumlevel: Building parameters for scope 'franklin' at sumlevel '140'.
2026-05-12 10:59:26,631 | INFO | morpc_census.geos.geoinfo_from_scope_sumlevel: SumLevel 'tract' specified for scope 'franklin'.
2026-05-12 10:59:26,633 | DEBUG | morpc_census.geos.pseudos_from_scope_sumlevel: Getting pseudo combinations for parents in 'franklin' at sumlevel 'tract'
2026-05-12 10:59:26,634 | INFO | morpc_census.geos.pseudos_from_scope_sumlevel: Returning pseudos for 1400000 in [GeoIDFQ(sumlevel='050', variant='00', geocomp='00', state='39', county='049')]
2026-05-12 10:59:26,636 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-countytract-franklin-b05006.__init__: Fetching data from https://api.census.gov/data/2023/acs/acs5? with params {'get': 'group(B05006)', 'ucgid': 'pseudo(0500000US39049$1400000)'}.
2026-05-12 10:59:26,638 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-countytract-franklin-b05006._fetch_group: Fetching group(B05006) — all variables, no limit.
2026-05-12 10:59:26,639 | DEBUG | morpc.req.get_text_safely: Getting data from https://api.census.gov/data/2023/acs/acs5?get=group(B05006)&ucgid=pseudo(0500000US39049$1400000)&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 with parameters None.
2026-05-12 10:59:26,641 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:27,465 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5?get=group(B05006)&ucgid=pseudo(0500000US39049$1400000)&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 10:59:28,617 | DEBUG | morpc.req.get_text_safely: Request successful. Returning plain text.
2026-05-12 10:59:28,708 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-countytract-franklin-b05006.melt: Melting data to long format.
2026-05-12 10:59:28,894 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups/B05006.json with parameters {'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:59:28,895 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:29,063 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups/B05006.json?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 26163
2026-05-12 10:59:29,131 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.

,geoidfq,name,reference_period,survey,concept,universe,variable_label,variable,estimate,moe
0,1400000US39049000110,Census Tract 1.10; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:,B05006_001,60,37
125,1400000US39049000110,Census Tract 1.10; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Europe:,B05006_002,17,19
145,1400000US39049000110,Census Tract 1.10; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Europe:!!Northern Europe:,B05006_003,12,18
146,1400000US39049000110,Census Tract 1.10; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Europe:!!Northern Europe:!!Denmark,B05006_004,0,13
147,1400000US39049000110,Census Tract 1.10; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Europe:!!Northern Europe:!!Ireland,B05006_005,0,13
...,...,...,...,...,...,...,...,...,...,...
58279,1400000US39049980000,Census Tract 9800; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Latin America:!!South Ameri...,B05006_174,0,13
58276,1400000US39049980000,Census Tract 9800; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Latin America:!!South Ameri...,B05006_175,0,13
58280,1400000US39049980000,Census Tract 9800; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Northern America:,B05006_176,0,13
58281,1400000US39049980000,Census Tract 9800; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Northern America:!!Canada,B05006_177,0,13
58282,1400000US39049980000,Census Tract 9800; Franklin County; Ohio,2023,acs/acs5,Place of birth for the foreign-born population...,Foreign-born population excluding population b...,Total:!!Americas:!!Northern America:!!Other No...,B05006_178,0,13

## 8. Fetching specific variables without a group

When you only need a few variables — possibly from different groups — pass `variables` directly instead of a group. The Census API allows at most 50 fields per request; the package batches automatically when you exceed that limit.

In [16]:
# Total population, male, and female — fetched directly without a group
pop = CensusAPI(ep, 'region15', variables=['B01001_001E', 'B01001_002E', 'B01001_026E'])
pop.long

2026-05-12 10:59:33,273 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-select-variables.__init__: Initializing CensusAPI for census-acs-acs5-2023-region15-select-variables.
2026-05-12 10:59:33,274 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-select-variables.__init__: Building request URL and parameters.
2026-05-12 10:59:33,275 | DEBUG | morpc_census.geos.geoids_from_scope: Fetching geoids from scope 'region15'.
2026-05-12 10:59:33,279 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/geoinfo?get=GEO_ID with parameters {'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141', 'in': 'state:39', 'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:59:33,282 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:33,715 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/geoinfo?get=GEO_ID&for=county%3A041%2C045%2C049%2C089%2C097%2C129%2C159%2C083%2C101%2C117%2C047%2C073%2C091%2C127%2C141&in=state%3A39&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 10:59:33,716 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-05-12 10:59:33,718 | DEBUG | morpc_census.geos.geoinfo_from_scope_sumlevel: Building parameters for scope 'region15' at sumlevel None.
2026-05-12 10:59:33,718 | INFO | morpc_census.geos.geoinfo_from_scope_sumlevel: No sumlevel specified; using scope 'region15' parameters.
2026-05-12 10:59:33,719 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-select-variables.__init__: Fetching data from https://api.census.gov/data/2023/acs/acs5? with params {'get': 'B01001_001E,B01001_002E,B01001_026E', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141', 'in': 'state:39'}.
2026-05-12 10:59:33,720 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-select-variables._fetch_variables: Fetching 3 variable(s) in 1 batch(es).
2026-05-12 10:59:33,721 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-select-variables._fetch_variables: Batch 1/1: 3 variable(s).
2026-05-12 10:59:33,722 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5? with parameters {'get': 'GEO_ID,B01001_001E,B01001_002E,B01001_026E', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141', 'in': 'state:39', 'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:59:33,723 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:34,344 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5?get=GEO_ID%2CB01001_001E%2CB01001_002E%2CB01001_026E&for=county%3A041%2C045%2C049%2C089%2C097%2C129%2C159%2C083%2C101%2C117%2C047%2C073%2C091%2C127%2C141&in=state%3A39&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 10:59:34,345 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-05-12 10:59:34,351 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-select-variables.melt: Melting data to long format.
2026-05-12 10:59:34,357 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups/B01001.json with parameters {'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 10:59:34,358 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 10:59:34,579 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups/B01001.json?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 19404
2026-05-12 10:59:34,611 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.

,geoidfq,reference_period,survey,concept,universe,variable_label,variable,estimate
0,0500000US39041,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,221160
2,0500000US39041,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,110668
1,0500000US39041,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,110492
3,0500000US39045,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,161289
5,0500000US39045,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,80584
4,0500000US39045,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,80705
6,0500000US39047,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,28880
8,0500000US39047,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,14271
7,0500000US39047,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,14609
9,0500000US39049,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,1321635
11,0500000US39049,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,649003
10,0500000US39049,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,672632
12,0500000US39073,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,27938
14,0500000US39073,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,14022
13,0500000US39073,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,13916
15,0500000US39083,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,62888
17,0500000US39083,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,31021
16,0500000US39083,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,31867
18,0500000US39089,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,180311
20,0500000US39089,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,89196
19,0500000US39089,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,91115
21,0500000US39091,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,46140
23,0500000US39091,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,23206
22,0500000US39091,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,22934
24,0500000US39097,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,44126
26,0500000US39097,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,24262
25,0500000US39097,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,19864
27,0500000US39101,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,65145
29,0500000US39101,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,35012
28,0500000US39101,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,30133
30,0500000US39117,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,35214
32,0500000US39117,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,17792
31,0500000US39117,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,17422
33,0500000US39127,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,35474
35,0500000US39127,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,17781
34,0500000US39127,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,17693
36,0500000US39129,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,59407
38,0500000US39129,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,31203
37,0500000US39129,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,28204
39,0500000US39141,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,76748
41,0500000US39141,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,40007
40,0500000US39141,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,36741
42,0500000US39159,2023,acs/acs5,,Not defined — no group specified,Total:,B01001_001,65293
44,0500000US39159,2023,acs/acs5,,Not defined — no group specified,Total:!!Male:,B01001_002,31579
43,0500000US39159,2023,acs/acs5,,Not defined — no group specified,Total:!!Female:,B01001_026,33714

## 9. Analyzing with DimensionTable

`DimensionTable` parses each variable's `!!`-delimited label into named **dimension columns** and pivots the long-format data into a readable wide table.

Each label segment is classified as a *subtotal* (ends with `:`) or a *leaf* (no trailing `:`). Subtotals are left-aligned into the first columns; leaves into the last. This alignment keeps the same concept in the same column regardless of path depth — for example, in B05004 (Nativity and Citizenship × Sex), *Male* and *Female* always land in the last column whether there are one or two nativity levels before them.

For B01001 (Sex by Age), `Total:!!Male:!!Under 5 years` parses as:

| dim | value |
|-----|-------|
| `total` | `Total:` |
| `sex` | `Male:` |
| `age` | `Under 5 years` |

Key methods:
- `drop(dim, method='summarize')` — remove a dimension level before pivoting
- `remap(variable_map)` — relabel and collapse variables, then re-parse dimensions
- `wide()` — produce the wide pivot table
- `percent()` — column percentages relative to the grand total row

In [17]:
# Construct a DimensionTable; dim_names labels the parsed dimension columns
dim = DimensionTable(b01001.long, dim_names=['total', 'sex', 'age'])

# Each row is one Census variable; each column is a level of the label hierarchy
# ':' suffix is preserved here — it marks subtotals (rows that have sub-dimensions)
dim.dims.head(8)

             total    sex              age
variable
B01001_001  Total:
B01001_002  Total:  Male:
B01001_003  Total:  Male:    Under 5 years
B01001_004  Total:  Male:     5 to 9 years
B01001_005  Total:  Male:   10 to 14 years
B01001_006  Total:  Male:   15 to 17 years
B01001_007  Total:  Male:  18 and 19 years
B01001_008  Total:  Male:         20 years

In [18]:
# Full wide table — all dimension levels as row index, geography × value type as columns
# ':' is stripped from displayed index values (Total: → Total, Male: → Male, etc.)
dim.wide()

                                            estimate                   moe  \
geoidfq                               0500000US39041        0500000US39041
name                           Delaware County, Ohio Delaware County, Ohio
reference_period                                2023                  2023
survey                                      acs/acs5              acs/acs5
concept                                   Sex by age            Sex by age
universe                            Total population      Total population
total sex    age
Total                                         221160            -555555555
      Male                                    110668                    33
             Under 5 years                      6456                     6
             5 to 9 years                       7560                   466
             10 to 14 years                     9200                   465
             15 to 17 years                     5478                    22
             18 and 19 years                    3068                   176
             20 years                           1337                   298
             21 years                           1490                   305
             22 to 24 years                     3434                   362
             25 to 29 years                     4556                   140
             30 to 34 years                     5846                    20
             35 to 39 years                     7477                   606
             40 to 44 years                     9403                   609
             45 to 49 years                     8681                    19
             50 to 54 years                     8309                    26
             55 to 59 years                     7351                   547
             60 and 61 years                    2678                   457
             62 to 64 years                     3255                   382
             65 and 66 years                    2304                   346
             67 to 69 years                     2872                   310
             70 to 74 years                     4734                   364
             75 to 79 years                     2642                   284
             80 to 84 years                     1212                   179
             85 years and over                  1325                   273
      Female                                  110492                    33
             Under 5 years                      6078                    23
             5 to 9 years                       7775                   413
             10 to 14 years                     8150                   411
             15 to 17 years                     5177                    19
             18 and 19 years                    2782                    97
             20 years                           1353                   306
             21 years                           1370                   325
             22 to 24 years                     3133                   410
             25 to 29 years                     4701                   136
             30 to 34 years                     6186                    85
             35 to 39 years                     8321                   550
             40 to 44 years                     8575                   547
             45 to 49 years                     8251                    15
             50 to 54 years                     7863                    15
             55 to 59 years                     7343                   397
             60 and 61 years                    2459                   309
             62 to 64 years                     3557                   393
             65 and 66 years                    2722                   274
             67 to 69 years                     2937                   359
             70 to 74 years                     4738                   375
             75 to 79 years                     3408                   347
             80 to 84 years                     1604                   290
             85 years and over                  2009                   352

                                             estimate                    moe  \
geoidfq                                0500000US39045         0500000US39045
name                           Fairfield County, Ohio Fairfield County, Ohio
reference_period                                 2023                   2023
survey                                       acs/acs5               acs/acs5
concept                                    Sex by age             Sex by age
universe                             Total population       Total population
total sex    age
Total                                          161289             -555555555
      Male                                      80584                    128
             Under 5 years                       4690                     86
             5 to 9 years                        5634                    510
             10 to 14 years                      5865                    510
             15 to 17 years                      3637                     93
             18 and 19 years                     1976                     87
             20 years                            1096                    224
             21 years                             857                    227
             22 to 24 years                      3135                    294
             25 to 29 years                      4917                     90
             30 to 34 years                      4917                     78
             35 to 39 years                      5557                    467
             40 to 44 years                      5248                    513
             45 to 49 years                      5266                    108
             50 to 54 years                      5460                    105
             55 to 59 years                      5779                    382
             60 and 61 years                     1832                    286
             62 to 64 years                      2844                    297
             65 and 66 years                     1912                    241
             67 to 69 years                      2251                    263
             70 to 74 years                      3185                    259
             75 to 79 years                      1901                    222
             80 to 84 years                      1497                    174
             85 years and over                   1128                    216
      Female                                    80705                    128
             Under 5 years                       4611                     86
             5 to 9 years                        4596                    406
             10 to 14 years                      6108                    406
             15 to 17 years                      3457                     93
             18 and 19 years                     1580                    170
             20 years                             867                    206
             21 years                             974                    231
             22 to 24 years                      2559                    294
             25 to 29 years                      4441                    120
             30 to 34 years                      5011                     87
             35 to 39 years                      5452                    382
             40 to 44 years                      5453                    384
             45 to 49 years                      5091                    116
             50 to 54 years                      5327                     62
             55 to 59 years                      5146                    449
             60 and 61 years                     2607                    371
             62 to 64 years                      2852                    406
             65 and 66 years                     1783                    243
             67 to 69 years                      2845                    327
             70 to 74 years                      3635                    318
             75 to 79 years                      2575                    249
             80 to 84 years                      1843                    241
             85 years and over                   1892                    225

                                           estimate                  moe  \
geoidfq                              0500000US39047       0500000US39047
name                           Fayette County, Ohio Fayette County, Ohio
reference_period                               2023                 2023
survey                                     acs/acs5             acs/acs5
concept                                  Sex by age           Sex by age
universe                           Total population     Total population
total sex    age
Total                                         28880           -555555555
      Male                                    14271                  163
             Under 5 years                      778                   22
             5 to 9 years                      1031                  145
             10 to 14 years                     998                  163
             15 to 17 years                     716                   62
             18 and 19 years                    324                   34
             20 years                           147                  105
             21 years                           159                  110
             22 to 24 years                     536                   93
             25 to 29 years                    1025                   95
             30 to 34 years                     829                   39
             35 to 39 years                     713                  179
             40 to 44 years                     922                  185
             45 to 49 years                     864                   36
             50 to 54 years                    1045                  150
             55 to 59 years                     907                  115
             60 and 61 years                    358                   98
             62 to 64 years                     594                  112
             65 and 66 years                    317                  114
             67 to 69 years                     271                   87
             70 to 74 years                     915                  116
             75 to 79 years                     245                   95
             80 to 84 years                     432                  125
             85 years and over                  145                   74
      Female                                  14609                  163
             Under 5 years                      840                   44
             5 to 9 years                       831                  143
             10 to 14 years                    1011                  136
             15 to 17 years                     638                   77
             18 and 19 years                    251                   24
             20 years                           172                   82
             21 years                           118                   75
             22 to 24 years                     542                   99
             25 to 29 years                     831                   57
             30 to 34 years                     898                   90
             35 to 39 years                     756                  145
             40 to 44 years                     902                  156
             45 to 49 years                     949                   80
             50 to 54 years                     953                   37
             55 to 59 years                    1070                  190
             60 and 61 years                    329                  108
             62 to 64 years                     668                  130
             65 and 66 years                    287                   99
             67 to 69 years                     599                  138
             70 to 74 years                     801                  150
             75 to 79 years                     496                  118
             80 to 84 years                     315                  106
             85 years and over                  352                   91

                                            estimate                   moe  \
geoidfq                               0500000US39049        0500000US39049
name                           Franklin County, Ohio Franklin County, Ohio
reference_period                                2023                  2023
survey                                      acs/acs5              acs/acs5
concept                                   Sex by age            Sex by age
universe                            Total population      Total population
total sex    age
Total                                        1321635            -555555555
      Male                                    649003                    61
             Under 5 years                     44950                    25
             5 to 9 years                      43653                  1413
             10 to 14 years                    43929                  1413
             15 to 17 years                    24640                    23
             18 and 19 years                   18955                   286
             20 years                           9355                   862
             21 years                           8310                   768
             22 to 24 years                    25751                  1043
             25 to 29 years                    56992                    87
             30 to 34 years                    58918                   114
             35 to 39 years                    48849                  1653
             40 to 44 years                    44621                  1666
             45 to 49 years                    38160                    76
             50 to 54 years                    38186                     2
             55 to 59 years                    36668                  1144
             60 and 61 years                   14284                   894
             62 to 64 years                    19981                  1000
             65 and 66 years                   11922                   819
             67 to 69 years                    15776                   899
             70 to 74 years                    20296                   843
             75 to 79 years                    11638                   642
             80 to 84 years                     6409                   474
             85 years and over                  6760                   579
      Female                                  672632                    61
             Under 5 years                     43192                    38
             5 to 9 years                      41693                  1178
             10 to 14 years                    42777                  1172
             15 to 17 years                    24090                    53
             18 and 19 years                   18410                   252
             20 years                           9220                   798
             21 years                           8122                   506
             22 to 24 years                    27263                   937
             25 to 29 years                    58356                    51
             30 to 34 years                    58857                    22
             35 to 39 years                    49378                  1664
             40 to 44 years                    43674                  1659
             45 to 49 years                    38606                    23
             50 to 54 years                    38247                     5
             55 to 59 years                    36746                  1241
             60 and 61 years                   16777                  1091
             62 to 64 years                    22039                  1030
             65 and 66 years                   13873                   761
             67 to 69 years                    18306                   845
             70 to 74 years                    25166                   944
             75 to 79 years                    15919                   818
             80 to 84 years                    10747                   692
             85 years and over                 11174                   747

                                           estimate                  moe  ...  \
geoidfq                              0500000US39073       0500000US39073  ...
name                           Hocking County, Ohio Hocking County, Ohio  ...
reference_period                               2023                 2023  ...
survey                                     acs/acs5             acs/acs5  ...
concept                                  Sex by age           Sex by age  ...
universe                           Total population     Total population  ...
total sex    age                                                          ...
Total                                         27938           -555555555  ...
      Male                                    14022                  110  ...
             Under 5 years                      808                   48  ...
             5 to 9 years                       666                  182  ...
             10 to 14 years                    1088                  197  ...
             15 to 17 years                     552                   20  ...
             18 and 19 years                    324                   32  ...
             20 years                           224                   86  ...
             21 years                           214                  132  ...
             22 to 24 years                     320                  121  ...
             25 to 29 years                     798                   42  ...
             30 to 34 years                     816                   40  ...
             35 to 39 years                     883                  178  ...
             40 to 44 years                     776                  180  ...
             45 to 49 years                     850                   24  ...
             50 to 54 years                     987                   26  ...
             55 to 59 years                    1011                  155  ...
             60 and 61 years                    435                  138  ...
             62 to 64 years                     666                  133  ...
             65 and 66 years                    369                  118  ...
             67 to 69 years                     488                  117  ...
             70 to 74 years                     762                  128  ...
             75 to 79 years                     420                  109  ...
             80 to 84 years                     402                  117  ...
             85 years and over                  163                   75  ...
      Female                                  13916                  110  ...
             Under 5 years                      703                   34  ...
             5 to 9 years                       975                  197  ...
             10 to 14 years                     715                  206  ...
             15 to 17 years                     545                   22  ...
             18 and 19 years                    273                   15  ...

In [19]:
# Drop the age dimension: keep only the pre-computed sex-level rows
# (grand total + Male total + Female total — one row per sex per county)
dim.drop('age').wide()

                              estimate                   moe  \
geoidfq                 0500000US39041        0500000US39041
name             Delaware County, Ohio Delaware County, Ohio
reference_period                  2023                  2023
survey                        acs/acs5              acs/acs5
concept                     Sex by age            Sex by age
universe              Total population      Total population
total sex
Total                           221160            -555555555
      Male                      110668                    33
      Female                    110492                    33

                               estimate                    moe  \
geoidfq                  0500000US39045         0500000US39045
name             Fairfield County, Ohio Fairfield County, Ohio
reference_period                   2023                   2023
survey                         acs/acs5               acs/acs5
concept                      Sex by age             Sex by age
universe               Total population       Total population
total sex
Total                            161289             -555555555
      Male                        80584                    128
      Female                      80705                    128

                             estimate                  moe  \
geoidfq                0500000US39047       0500000US39047
name             Fayette County, Ohio Fayette County, Ohio
reference_period                 2023                 2023
survey                       acs/acs5             acs/acs5
concept                    Sex by age           Sex by age
universe             Total population     Total population
total sex
Total                           28880           -555555555
      Male                      14271                  163
      Female                    14609                  163

                              estimate                   moe  \
geoidfq                 0500000US39049        0500000US39049
name             Franklin County, Ohio Franklin County, Ohio
reference_period                  2023                  2023
survey                        acs/acs5              acs/acs5
concept                     Sex by age            Sex by age
universe              Total population      Total population
total sex
Total                          1321635            -555555555
      Male                      649003                    61
      Female                    672632                    61

                             estimate                  moe  ...  \
geoidfq                0500000US39073       0500000US39073  ...
name             Hocking County, Ohio Hocking County, Ohio  ...
reference_period                 2023                 2023  ...
survey                       acs/acs5             acs/acs5  ...
concept                    Sex by age           Sex by age  ...
universe             Total population     Total population  ...
total sex                                                   ...
Total                           27938           -555555555  ...
      Male                      14022                  110  ...
      Female                    13916                  110  ...

                            estimate                 moe           estimate  \
geoidfq               0500000US39117      0500000US39117     0500000US39127
name             Morrow County, Ohio Morrow County, Ohio Perry County, Ohio
reference_period                2023                2023               2023
survey                      acs/acs5            acs/acs5           acs/acs5
concept                   Sex by age          Sex by age         Sex by age
universe            Total population    Total population   Total population
total sex
Total                          35214          -555555555              35474
      Male                     17792                  87              17781
      Female                   17422                  87              17693

                                moe              estimate  \
geoidfq              0500000US39127        0500000US39129
name             Perry County, Ohio Pickaway County, Ohio
reference_period               2023                  2023
survey                     acs/acs5              acs/acs5
concept                  Sex by age            Sex by age
universe           Total population      Total population
total sex
Total                    -555555555                 59407
      Male                       82                 31203
      Female                     82                 28204

                                   moe          estimate               moe  \
geoidfq                 0500000US39129    0500000US39141    0500000US39141
name             Pickaway County, Ohio Ross County, Ohio Ross County, Ohio
reference_period                  2023              2023              2023
survey                        acs/acs5          acs/acs5          acs/acs5
concept                     Sex by age        Sex by age        Sex by age
universe              Total population  Total population  Total population
total sex
Total                       -555555555             76748        -555555555
      Male                         136             40007               190
      Female                       136             36741               190

                           estimate                moe
geoidfq              0500000US39159     0500000US39159
name             Union County, Ohio Union County, Ohio
reference_period               2023               2023
survey                     acs/acs5           acs/acs5
concept                  Sex by age         Sex by age
universe           Total population   Total population
total sex
Total                         65293         -555555555
      Male                    31579                124
      Female                  33714                124

[3 rows x 30 columns]

In [20]:
from morpc_census import AGEGROUP_MAP

# B01001 uses uneven age bins: "15 to 17 years" and "18 and 19 years" are separate
# variables, as are "20 years", "21 years", and "22 to 24 years".
# AGEGROUP_MAP collapses these into standard 5-year groups. remap() applies the
# substitutions and sums estimates for any rows that share a new label.
dim_remapped = DimensionTable(b01001.long, dim_names=['total', 'sex', 'age'])
dim_remapped.remap(AGEGROUP_MAP)

# Population by standardized age group — aggregate sex out (sum Male + Female)
dim_remapped.drop('sex', method='aggregate').wide()

2026-05-12 11:00:06,920 | INFO | morpc_census.api.DimensionTable.remap: Remapping variables: ['Under 5 years', '5 to 9 years', '10 to 14 years', '15 to 17 years', '18 and 19 years', '20 years', '21 years', '22 to 24 years', '25 to 29 years', '30 to 34 years', '35 to 39 years', '40 to 44 years', '45 to 49 years', '50 to 54 years', '55 to 59 years', '60 and 61 years', '62 to 64 years', '65 and 66 years', '67 to 69 years', '70 to 74 years', '75 to 79 years', '80 to 84 years', '85 years and over'].

                                     estimate                   moe  \
geoidfq                        0500000US39041        0500000US39041
name                    Delaware County, Ohio Delaware County, Ohio
reference_period                         2023                  2023
survey                               acs/acs5              acs/acs5
concept                            Sex by age            Sex by age
universe                     Total population      Total population
total age
Total                                221160.0             46.669048
      10 to 14 years                  17350.0            620.601321
      15 to 19 years                  16505.0            203.051718
      20 to 24 years                  12117.0            824.762996
      25 to 29 years                   9257.0            195.181966
      30 to 34 years                  12032.0             87.321246
      35 to 39 years                  15798.0            818.373998
      40 to 44 years                  17978.0            818.590252
      45 to 49 years                  16932.0             24.207437
      5 to 9 years                    15335.0            622.675678
      50 to 54 years                  16172.0             30.016662
      55 to 59 years                  14694.0            675.883126
      60 to 64 years                  11949.0            777.626517
      65 to 69 years                  10835.0            647.898912
      70 to 74 years                   9472.0            522.609797
      75 to 79 years                   6050.0            448.402721
      80 to 84 years                   2816.0            340.794660
      85 years and over                3334.0            445.458191
      Under 5 years                   12534.0             23.769729

                                      estimate                    moe  \
geoidfq                         0500000US39045         0500000US39045
name                    Fairfield County, Ohio Fairfield County, Ohio
reference_period                          2023                   2023
survey                                acs/acs5               acs/acs5
concept                             Sex by age             Sex by age
universe                      Total population       Total population
total age
Total                                 161289.0             181.019336
      10 to 14 years                   11973.0             651.871153
      15 to 19 years                   10650.0             231.877123
      20 to 24 years                    9488.0             608.583601
      25 to 29 years                    9358.0             150.000000
      30 to 34 years                    9928.0             116.846053
      35 to 39 years                   11009.0             603.334899
      40 to 44 years                   10701.0             640.800281
      45 to 49 years                   10357.0             158.492902
      5 to 9 years                     10230.0             651.871153
      50 to 54 years                   10787.0             121.938509
      55 to 59 years                   10925.0             589.512510
      60 to 64 years                   10135.0             687.373261
      65 to 69 years                    8791.0             541.505309
      70 to 74 years                    6820.0             410.128029
      75 to 79 years                    4476.0             333.594065
      80 to 84 years                    3340.0             297.249054
      85 years and over                 3020.0             311.899022
      Under 5 years                     9301.0             121.622366

                                    estimate                  moe  \
geoidfq                       0500000US39047       0500000US39047
name                    Fayette County, Ohio Fayette County, Ohio
reference_period                        2023                 2023
survey                              acs/acs5             acs/acs5
concept                           Sex by age           Sex by age
universe                    Total population     Total population
total age
Total                                28880.0           230.516811
      10 to 14 years                  2009.0           212.285186
      15 to 19 years                  1929.0           107.261363
      20 to 24 years                  1674.0           232.215417
      25 to 29 years                  1856.0           110.788086
      30 to 34 years                  1727.0            98.086696
      35 to 39 years                  1469.0           230.360587
      40 to 44 years                  1824.0           241.993802
      45 to 49 years                  1813.0            87.726849
      5 to 9 years                    1862.0           203.651663
      50 to 54 years                  1998.0           154.495955
      55 to 59 years                  1977.0           222.092323
      60 to 64 years                  1949.0           225.193250
      65 to 69 years                  1474.0           222.283603
      70 to 74 years                  1716.0           189.620674
      75 to 79 years                   741.0           151.489274
      80 to 84 years                   747.0           163.893258
      85 years and over                497.0           117.290238
      Under 5 years                   1618.0            49.193496

                                     estimate                   moe  \
geoidfq                        0500000US39049        0500000US39049
name                    Franklin County, Ohio Franklin County, Ohio
reference_period                         2023                  2023
survey                               acs/acs5              acs/acs5
concept                            Sex by age            Sex by age
universe                     Total population      Total population
total age
Total                               1321635.0             86.267027
      10 to 14 years                  86706.0           1835.797647
      15 to 19 years                  86095.0            385.535991
      20 to 24 years                  88021.0           2047.321665
      25 to 29 years                 115348.0            100.846418
      30 to 34 years                 117775.0            116.103402
      35 to 39 years                  98227.0           2345.486090
      40 to 44 years                  88295.0           2351.135258
      45 to 49 years                  76766.0             79.404030
      5 to 9 years                    85346.0           1839.633931
      50 to 54 years                  76433.0              5.385165
      55 to 59 years                  73414.0           1687.843891
      60 to 64 years                  73081.0           2012.564782
      65 to 69 years                  59877.0           1664.964864
      70 to 74 years                  45462.0           1265.616451
      75 to 79 years                  27557.0           1039.849989
      80 to 84 years                  17156.0            838.772913
      85 years and over               17934.0            945.119040
      Under 5 years                   88142.0             45.486262

                                    estimate                  moe  ...  \
geoidfq                       0500000US39073       0500000US39073  ...
name                    Hocking County, Ohio Hocking County, Ohio  ...
reference_period                        2023                 2023  ...
survey                              acs/acs5             acs/acs5  ...
concept                           Sex by age           Sex by age  ...
universe                    Total population     Total population  ...
total age                                                          ...
Total                                27938.0           155.563492  ...
      10 to 14 years                  1803.0           285.035086  ...
      15 to 19 years                  1694.0            46.184413  ...
      20 to 24 years                  1450.0           256.846258  ...
      25 to 29 years                  1561.0            42.953463  ...
      30 to 34 years                  1588.0            47.707442  ...
      35 to 39 years                  1929.0           232.774569  ...
      40 to 44 years                  1340.0           231.138487  ...
      45 to 49 years                  1737.0            37.643060  ...
      5 to 9 years                    1641.0           268.203281  ...
      50 to 54 years                  1959.0            53.712196  ...
      55 to 59 years                  2160.0           230.054341  ...
      60 to 64 years                  2105.0           271.247120  ...
      65 to 69 years                  1707.0           228.687560  ...
      70 to 74 years                  1573.0           174.091930  ...
      75 to 79 years                  1070.0           171.187032  ...
      80 to 84 years                   699.0           155.219200  ...
      85 years and over                411.0           114.865138  ...
      Under 5 years                   1511.0            58.821765  ...

                                   estimate                 moe  \
geoidfq                      0500000US39117      0500000US39117
name                    Morrow County, Ohio Morrow County, Ohio
reference_period                       2023                2023
survey                             acs/acs5            acs/acs5
concept                          Sex by age          Sex by age
universe                   Total population    Total population
total age
Total                               35214.0          123.036580
      10 to 14 years                 2356.0          239.420133
      15 to 19 years                 2271.0           71.547187
      20 to 24 years                 1777.0          263.626630
      25 to 29 years                 1902.0           82.879430
      30 to 34 years                 2025.0           69.835521
      35 to 39 years                 1896.0          296.804650
      40 to 44 years                 2339.0          293.410975
      45 to 49 years                 2354.0           58.728187
      5 to 9 years                   1946.0          227.668619
      50 to 54 years                 2454.0           22.671568
      55 to 59 years                 2564.0          256.850151
      60 to 64 years                 2771.0          341.732351
      65 to 69 years                 2452.0          309.677251
      70 to 74 years                 1642.0          220.510771
      75 to 79 years                 1155.0          173.643313
      80 to 84 years                  882.0          159.665275
      85 years and over               471.0          123.664870
      Under 5 years                  1957.0           69.310894

                                  estimate                moe  \
geoidfq                     0500000US39127     0500000US39127
name                    Perry County, Ohio Perry County, Ohio
reference_period                      2023               2023
survey                            acs/acs5           acs/acs5
concept                         Sex by age         Sex by age
universe                  Total population   Total population
total age
Total                              35474.0         115.965512
      10 to 14 years                2496.0         251.143385
      15 to 19 years                2296.0          58.966092
      20 to 24 years                1808.0         237.472104
      25 to 29 years                2121.0          53.823787
      30 to 34 years                2148.0          56.400355
      35 to 39 years                1827.0         238.321212
      40 to 44 years                2443.0         237.075937
      45 to 49 years                2227.0          52.478567
      5 to 9 years                  2216.0         247.491414
      50 to 54 years                2370.0          20.518285
      55 to 59 years                2672.0         242.639651
      60 to 64 years                2394.0         295.206707
      65 to 69 years                2479.0         271.488490
      70 to 74 years                1554.0         198.171643
      75 to 79 years                1060.0         149.281613
      80 to 84 years                 773.0         145.725770
      85 years and over              489.0          98.310732
      Under 5 years                 2101.0          52.345009

                                     estimate                   moe  \
geoidfq                        0500000US39129        0500000US39129
name                    Pickaway County, Ohio Pickaway County, Ohio
reference_period                         2023                  2023
survey                               acs/acs5              acs/acs5
concept                            Sex by age            Sex by age
universe                     Total population      Total population
total age
Total                                 59407.0            192.333044
      10 to 14 years                   3679.0            366.259471
      15 to 19 years                   3913.0            256.011718
      20 to 24 years                   3556.0            434.158957
      25 to 29 years                   3904.0            112.089250
      30 to 34 years                   4105.0            120.552893
      35 to 39 years                   4234.0            326.710881
      40 to 44 years                   3940.0            319.037615
      45 to 49 years                   3968.0            114.389685
      5 to 9 years                     3541.0            362.200221
      50 to 54 years                   4095.0             45.880279
      55 to 59 years                   4138.0            305.499591
      60 to 64 years                   3622.0            352.370544
      65 to 69 years                   3034.0            322.133513
      70 to 74 years                   2700.0            256.534598
      75 to 79 years                   1653.0            188.353391
      80 to 84 years                   1322.0            210.411502
      85 years and over                 829.0            154.896740
      Under 5 years                    3174.0             75.604233

                                 estimate               moe  \
geoidfq                    0500000US39141    0500000US39141
name                    Ross County, Ohio Ross County, Ohio
reference_period                     2023              2023
survey                           acs/acs5          acs/acs5
concept                        Sex by age        Sex by age
universe                 Total population  Total population
total age
Total                             76748.0        268.700577
      10 to 14 years               5045.0        446.891486
      15 to 19 years               4350.0        173.660589
      20 to 24 years               4302.0        393.814677
      25 to 29 years               5119.0        141.650980
      30 to 34 years               4850.0        167.839209
      35 to 39 years               5316.0        417.310436
      40 to 44 years               4761.0        420.733883
      45 to 49 years               5028.0        139.946418
      5 to 9 years                 4125.0        413.010896
      50 to 54 years               5388.0        198.217053
      55 to 59 years               5287.0        478.539445
      60 to 64 years               5473.0        560.108918
      65 to 69 years               4609.0        427.356994
      70 to 74 years               3563.0        309.090602
      75 to 79 years               2198.0        253.464001
      80 to 84 years               1780.0        249.226804
      85 years and over            1282.0        223.143452
      Under 5 years                4272.0        148.499158

                                  estimate                moe
geoidfq                     0500000US39159     0500000US39159
name                    Union County, Ohio Union County, Ohio
reference_period                      2023               2023
survey                            acs/acs5           acs/acs5
concept                         Sex by age         Sex by age
universe                  Total population   Total population
total age
Total                              65293.0         175.362482
      10 to 14 years                4481.0         322.639117
      15 to 19 years                4421.0         170.836179
      20 to 24 years                3444.0         374.763926
      25 to 29 years                4015.0         194.699769
      30 to 34 years                4561.0         161.335055
      35 to 39 years                5103.0         395.733496
      40 to 44 years                5157.0         366.349560
      45 to 49 years                4598.0         119.016806
      5 to 9 years                  4419.0         360.635550
      50 to 54 years                4546.0         165.414631
      55 to 59 years                4441.0         359.918046
      60 to 64 years                3620.0         383.796821
      65 to 69 years                3273.0         394.784751
      70 to 74 years                1989.0         269.091063
      75 to 79 years                1323.0         193.868512
      80 to 84 years                1037.0         173.484870
      85 years and over              828.0         173.738309
      Under 5 years                 4037.0          86.556340

[19 rows x 30 columns]

In [21]:
# Sex percentages relative to the county total (age dropped; grand total = 100%)
dim.drop('age').percent()

                              estimate                   moe  \
geoidfq                 0500000US39041        0500000US39041
name             Delaware County, Ohio Delaware County, Ohio
reference_period                  2023                  2023
survey                        acs/acs5              acs/acs5
concept                     Sex by age            Sex by age
universe              Total population      Total population
total sex
Total Male                       50.04                  -0.0
      Female                     49.96                  -0.0

                               estimate                    moe  \
geoidfq                  0500000US39045         0500000US39045
name             Fairfield County, Ohio Fairfield County, Ohio
reference_period                   2023                   2023
survey                         acs/acs5               acs/acs5
concept                      Sex by age             Sex by age
universe               Total population       Total population
total sex
Total Male                        49.96                   -0.0
      Female                      50.04                   -0.0

                             estimate                  moe  \
geoidfq                0500000US39047       0500000US39047
name             Fayette County, Ohio Fayette County, Ohio
reference_period                 2023                 2023
survey                       acs/acs5             acs/acs5
concept                    Sex by age           Sex by age
universe             Total population     Total population
total sex
Total Male                      49.41                 -0.0
      Female                    50.59                 -0.0

                              estimate                   moe  \
geoidfq                 0500000US39049        0500000US39049
name             Franklin County, Ohio Franklin County, Ohio
reference_period                  2023                  2023
survey                        acs/acs5              acs/acs5
concept                     Sex by age            Sex by age
universe              Total population      Total population
total sex
Total Male                       49.11                  -0.0
      Female                     50.89                  -0.0

                             estimate                  moe  ...  \
geoidfq                0500000US39073       0500000US39073  ...
name             Hocking County, Ohio Hocking County, Ohio  ...
reference_period                 2023                 2023  ...
survey                       acs/acs5             acs/acs5  ...
concept                    Sex by age           Sex by age  ...
universe             Total population     Total population  ...
total sex                                                   ...
Total Male                      50.19                 -0.0  ...
      Female                    49.81                 -0.0  ...

                            estimate                 moe           estimate  \
geoidfq               0500000US39117      0500000US39117     0500000US39127
name             Morrow County, Ohio Morrow County, Ohio Perry County, Ohio
reference_period                2023                2023               2023
survey                      acs/acs5            acs/acs5           acs/acs5
concept                   Sex by age          Sex by age         Sex by age
universe            Total population    Total population   Total population
total sex
Total Male                     50.53                -0.0              50.12
      Female                   49.47                -0.0              49.88

                                moe              estimate  \
geoidfq              0500000US39127        0500000US39129
name             Perry County, Ohio Pickaway County, Ohio
reference_period               2023                  2023
survey                     acs/acs5              acs/acs5
concept                  Sex by age            Sex by age
universe           Total population      Total population
total sex
Total Male                     -0.0                 52.52
      Female                   -0.0                 47.48

                                   moe          estimate               moe  \
geoidfq                 0500000US39129    0500000US39141    0500000US39141
name             Pickaway County, Ohio Ross County, Ohio Ross County, Ohio
reference_period                  2023              2023              2023
survey                        acs/acs5          acs/acs5          acs/acs5
concept                     Sex by age        Sex by age        Sex by age
universe              Total population  Total population  Total population
total sex
Total Male                        -0.0             52.13              -0.0
      Female                      -0.0             47.87              -0.0

                           estimate                moe
geoidfq              0500000US39159     0500000US39159
name             Union County, Ohio Union County, Ohio
reference_period               2023               2023
survey                     acs/acs5           acs/acs5
concept                  Sex by age         Sex by age
universe           Total population   Total population
total sex
Total Male                    48.37               -0.0
      Female                  51.63               -0.0

[2 rows x 30 columns]

## 10. Time series

`DimensionTable` accepts any long-format DataFrame with the standard schema. Concatenating `long` from multiple vintages produces a time-series table where `reference_period` becomes a column dimension.

In [22]:
# Fetch the same group for an earlier vintage
ep2018 = Endpoint('acs/acs5', 2018)
b01001_2018 = CensusAPI(ep2018, 'region15', group=Group(ep2018, 'B01001'))

# Stack the two years and build a dimension table
long_ts = pd.concat([b01001_2018.long, b01001.long])
DimensionTable(long_ts).wide()

2026-05-12 11:00:09,909 | DEBUG | morpc_census.api.groups: Fetching groups for 2018 acs/acs5
2026-05-12 11:00:09,912 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2018/acs/acs5/groups.json with parameters {'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 11:00:09,915 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 11:00:10,117 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2018/acs/acs5/groups.json?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 11:00:10,478 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-05-12 11:00:10,486 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2018-region15-b01001.__init__: Initializing CensusAPI for census-acs-acs5-2018-region15-b01001.
2026-05-12 11:00:10,488 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2018-region15-b01001.__init__: Building request URL and parameters.
2026-05-12 11:00:10,489 | DEBUG | morpc_census.geos.geoids_from_scope: Fetching geoids from scope 'region15'.
2026-05-12 11:00:10,492 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/geoinfo?get=GEO_ID with parameters {'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141', 'in': 'state:39', 'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 11:00:10,495 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 11:00:10,899 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/geoinfo?get=GEO_ID&for=county%3A041%2C045%2C049%2C089%2C097%2C129%2C159%2C083%2C101%2C117%2C047%2C073%2C091%2C127%2C141&in=state%3A39&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 11:00:10,901 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-05-12 11:00:10,905 | DEBUG | morpc_census.geos.geoinfo_from_scope_sumlevel: Building parameters for scope 'region15' at sumlevel None.
2026-05-12 11:00:10,906 | INFO | morpc_census.geos.geoinfo_from_scope_sumlevel: No sumlevel specified; using scope 'region15' parameters.
2026-05-12 11:00:10,908 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2018-region15-b01001.__init__: Fetching data from https://api.census.gov/data/2018/acs/acs5? with params {'get': 'group(B01001)', 'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141', 'in': 'state:39'}.
2026-05-12 11:00:10,910 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2018-region15-b01001._fetch_group: Fetching group(B01001) — all variables, no limit.
2026-05-12 11:00:10,911 | DEBUG | morpc.req.get_text_safely: Getting data from https://api.census.gov/data/2018/acs/acs5?get=group(B01001)&for=county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141&in=state:39&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 with parameters None.
2026-05-12 11:00:10,914 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 11:00:11,379 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2018/acs/acs5?get=group(B01001)&for=county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141&in=state:39&key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 11:00:11,412 | DEBUG | morpc.req.get_text_safely: Request successful. Returning plain text.
2026-05-12 11:00:11,433 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2018-region15-b01001.melt: Melting data to long format.
2026-05-12 11:00:11,458 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2018/acs/acs5/groups/B01001.json with parameters {'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 11:00:11,461 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 11:00:11,680 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2018/acs/acs5/groups/B01001.json?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 18623
2026-05-12 11:00:11,712 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.
2026-05-12 11:00:11,737 | DEBUG | morpc_census.api.groups: Fetching groups for 2023 acs/acs5
2026-05-12 11:00:11,740 | DEBUG | morpc.req.get_json_safely: Getting data from https://api.census.gov/data/2023/acs/acs5/groups.json with parameters {'key': '83269ff2739cb3bd485c75b091dcee493ad6fe70'}.
2026-05-12 11:00:11,746 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): api.census.gov:443
2026-05-12 11:00:11,908 | DEBUG | urllib3.connectionpool._make_request: https://api.census.gov:443 "GET /data/2023/acs/acs5/groups.json?key=83269ff2739cb3bd485c75b091dcee493ad6fe70 HTTP/1.1" 200 None
2026-05-12 11:00:12,352 | DEBUG | morpc.req.get_json_safely: Request successful. Decoding return JSON.

                                            estimate                   \
geoidfq                               0500000US39041
name                           Delaware County, Ohio
reference_period                                2018             2023
survey                                      acs/acs5         acs/acs5
concept                                   Sex by age       Sex by age
universe                            Total population Total population
dim_0 dim_1  dim_2
Total                                         197008           221160
      Male                                     97504           110668
             Under 5 years                      6273             6456
             5 to 9 years                       7752             7560
             10 to 14 years                     8435             9200
             15 to 17 years                     4731             5478
             18 and 19 years                    2531             3068
             20 years                           1515             1337
             21 years                           1000             1490
             22 to 24 years                     2824             3434
             25 to 29 years                     3911             4556
             30 to 34 years                     5349             5846
             35 to 39 years                     7256             7477
             40 to 44 years                     7690             9403
             45 to 49 years                     8006             8681
             50 to 54 years                     7175             8309
             55 to 59 years                     6484             7351
             60 and 61 years                    2254             2678
             62 to 64 years                     2915             3255
             65 and 66 years                    1892             2304
             67 to 69 years                     2676             2872
             70 to 74 years                     2946             4734
             75 to 79 years                     1655             2642
             80 to 84 years                     1296             1212
             85 years and over                   938             1325
      Female                                   99504           110492
             Under 5 years                      6112             6078
             5 to 9 years                       7693             7775
             10 to 14 years                     7624             8150
             15 to 17 years                     4612             5177
             18 and 19 years                    2375             2782
             20 years                           1086             1353
             21 years                            973             1370
             22 to 24 years                     2928             3133
             25 to 29 years                     4177             4701
             30 to 34 years                     6046             6186
             35 to 39 years                     7589             8321
             40 to 44 years                     7861             8575
             45 to 49 years                     7741             8251
             50 to 54 years                     7104             7863
             55 to 59 years                     6412             7343
             60 and 61 years                    2287             2459
             62 to 64 years                     3262             3557
             65 and 66 years                    1653             2722
             67 to 69 years                     2828             2937
             70 to 74 years                     3630             4738
             75 to 79 years                     2458             3408
             80 to 84 years                     1479             1604
             85 years and over                  1574             2009

                                                 moe                   \
geoidfq                               0500000US39041
name                           Delaware County, Ohio
reference_period                                2018             2023
survey                                      acs/acs5         acs/acs5
concept                                   Sex by age       Sex by age
universe                            Total population Total population
dim_0 dim_1  dim_2
Total                                     -555555555       -555555555
      Male                                        74               33
             Under 5 years                        37                6
             5 to 9 years                        403              466
             10 to 14 years                      404              465
             15 to 17 years                       45               22
             18 and 19 years                     109              176
             20 years                            253              298
             21 years                            226              305
             22 to 24 years                      279              362
             25 to 29 years                      121              140
             30 to 34 years                       80               20
             35 to 39 years                      377              606
             40 to 44 years                      414              609
             45 to 49 years                      119               19
             50 to 54 years                       97               26
             55 to 59 years                      321              547
             60 and 61 years                     296              457
             62 to 64 years                      304              382
             65 and 66 years                     226              346
             67 to 69 years                      275              310
             70 to 74 years                      277              364
             75 to 79 years                      183              284
             80 to 84 years                      171              179
             85 years and over                   167              273
      Female                                      74               33
             Under 5 years                        27               23
             5 to 9 years                        448              413
             10 to 14 years                      456              411
             15 to 17 years                       47               19
             18 and 19 years                     115               97
             20 years                            274              306
             21 years                            241              325
             22 to 24 years                      316              410
             25 to 29 years                       69              136
             30 to 34 years                       18               85
             35 to 39 years                      410              550
             40 to 44 years                      404              547
             45 to 49 years                      116               15
             50 to 54 years                       62               15
             55 to 59 years                      342              397
             60 and 61 years                     263              309
             62 to 64 years                      299              393
             65 and 66 years                     200              274
             67 to 69 years                      279              359
             70 to 74 years                      299              375
             75 to 79 years                      231              347
             80 to 84 years                      212              290
             85 years and over                   177              352

                                             estimate                   \
geoidfq                                0500000US39045
name                           Fairfield County, Ohio
reference_period                                 2018             2023
survey                                       acs/acs5         acs/acs5
concept                                    Sex by age       Sex by age
universe                             Total population Total population
dim_0 dim_1  dim_2
Total                                          152910           161289
      Male                                      76254            80584
             Under 5 years                       4588             4690
             5 to 9 years                        5077             5634
             10 to 14 years                      5904             5865
             15 to 17 years                      3535             3637
             18 and 19 years                     1995             1976
             20 years                             941             1096
             21 years                             996              857
             22 to 24 years                      3133             3135
             25 to 29 years                      4681             4917
             30 to 34 years                      4491             4917
             35 to 39 years                      4738             5557
             40 to 44 years                      5098             5248
             45 to 49 years                      5526             5266
             50 to 54 years                      5478             5460
             55 to 59 years                      5178             5779
             60 and 61 years                     2075             1832
             62 to 64 years                      2491             2844
             65 and 66 years                     1645             1912
             67 to 69 years                      2325             2251
             70 to 74 years                      2406             3185
             75 to 79 years                      1886             1901
             80 to 84 years                      1139             1497
             85 years and over                    928             1128
      Female                                    76656            80705
             Under 5 years                       4401             4611
             5 to 9 years                        4921             4596
             10 to 14 years                      5217             6108
             15 to 17 years                      3405             3457
             18 and 19 years                     1650             1580
             20 years                             679              867
             21 years                             868              974
             22 to 24 years                      2657             2559
             25 to 29 years                      4186             4441
             30 to 34 years                      4624             5011
             35 to 39 years                      4995             5452
             40 to 44 years                      5071             5453
             45 to 49 years                      5385             5091
             50 to 54 years                      5628             5327
             55 to 59 years                      5163             5146
             60 and 61 years                     1995             2607
             62 to 64 years                      3032             2852
             65 and 66 years                     1915             1783
             67 to 69 years                      2330             2845
             70 to 74 years                      3023             3635
             75 to 79 years                      2200             2575
             80 to 84 years                      1754             1843
             85 years and over                   1557             1892

                                                  moe                   \
geoidfq                                0500000US39045
name                           Fairfield County, Ohio
reference_period                                 2018             2023
survey                                       acs/acs5         acs/acs5
concept                                    Sex by age       Sex by age
universe                             Total population Total population
dim_0 dim_1  dim_2
Total                                      -555555555       -555555555
      Male                                        118              128
             Under 5 years                         58               86
             5 to 9 years                         355              510
             10 to 14 years                       366              510
             15 to 17 years                        58               93
             18 and 19 years                       75               87
             20 years                             235              224
             21 years                             262              227
             22 to 24 years                       358              294
             25 to 29 years                       116               90
             30 to 34 years                        83               78
             35 to 39 years                       388              467
             40 to 44 years                       396              513
             45 to 49 years                        82              108
             50 to 54 years                        80              105
             55 to 59 years                       300              382
             60 and 61 years                      216              286
             62 to 64 years                       264              297
             65 and 66 years                      222              241
             67 to 69 years                       251              263
             70 to 74 years                       284              259
             75 to 79 years                       210              222
             80 to 84 years                       193              174
             85 years and over                    162              216
      Female                                      118              128
             Under 5 years                         64               86
             5 to 9 years                         378              406
             10 to 14 years                       378              406
             15 to 17 years                        61               93
             18 and 19 years                       64              170
             20 years                             188              206
             21 years                             220              231
             22 to 24 years                       251              294
             25 to 29 years                        92              120
             30 to 34 years                       110               87
             35 to 39 years                       321              382
             40 to 44 years                       369              384
             45 to 49 years                        89              116
             50 to 54 years                       136               62
             55 to 59 years                       312              449
             60 and 61 years                      249              371
             62 to 64 years                       256              406
             65 and 66 years                      240              243
             67 to 69 years                       215              327
             70 to 74 years                       284              318
             75 to 79 years                       250              249
             80 to 84 years                       219              241
             85 years and over                    207              225

                                           estimate                   ...  \
geoidfq                              0500000US39047                   ...
name                           Fayette County, Ohio                   ...
reference_period                               2018             2023  ...
survey                                     acs/acs5         acs/acs5  ...
concept                                  Sex by age       Sex by age  ...
universe                           Total population Total population  ...
dim_0 dim_1  dim_2                                                    ...
Total                                         28645            28880  ...
      Male                                    13960            14271  ...
             Under 5 years                      929              778  ...
             5 to 9 years                       967             1031  ...
             10 to 14 years                     945              998  ...
             15 to 17 years                     597              716  ...
             18 and 19 years                    297              324  ...
             20 years                           100              147  ...
             21 years                           178              159  ...
             22 to 24 years                     582              536  ...
             25 to 29 years                     926             1025  ...
             30 to 34 years                     752              829  ...
             35 to 39 years                     822              713  ...
             40 to 44 years                     916              922  ...
             45 to 49 years                     965              864  ...
             50 to 54 years                     952             1045  ...
             55 to 59 years                    1011              907  ...
             60 and 61 years                    395              358  ...
             62 to 64 years                     444              594  ...
             65 and 66 years                    324              317  ...
             67 to 69 years                     413              271  ...
             70 to 74 years                     628              915  ...
             75 to 79 years                     444              245  ...
             80 to 84 years                     235              432  ...
             85 years and over                  138              145  ...
      Female                                  14685            14609  ...
             Under 5 years                      844              840  ...
             5 to 9 years                       976              831  ...
             10 to 14 years                    1034             1011  ...
             15 to 17 years                     557              638  ...
             18 and 19 years                    275              251  ...
             20 years                           197              172  ...
             21 years                            90              118  ...
             22 to 24 years                     522              542  ...
             25 to 29 years                     832              831  ...
             30 to 34 years                     856              898  ...
             35 to 39 years                     835              756  ...
             40 to 44 years                     982              902  ...
             45 to 49 years                    1014              949  ...
             50 to 54 years                     948              953  ...
             55 to 59 years                    1080             1070  ...
             60 and 61 years                    291              329  ...
             62 to 64 years                     676              668  ...
             65 and 66 years                    390              287  ...
             67 to 69 years                     515              599  ...
             70 to 74 years                     607              801  ...
             75 to 79 years                     444              496  ...
             80 to 84 years                     382              315  ...
             85 years and over                  338              352  ...


## 11. Saving output

`api.save()` writes three files to the output directory:

- `{name}.long.csv` — the long-format data
- `{name}.schema.yaml` — a frictionless Schema describing every column
- `{name}.resource.yaml` — a frictionless Resource descriptor linking the CSV to its schema

The resource is validated immediately after writing, so any schema mismatch surfaces here.

In [23]:
import os

b01001.save('./temp_data')

print('filename:', b01001.filename)
print('exists:  ', os.path.exists(f'./temp_data/{b01001.filename}'))

2026-05-12 11:00:17,318 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001.save: Writing data to temp_data/census-acs-acs5-2023-region15-b01001.long.csv.
2026-05-12 11:00:17,326 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001.save: Writing schema to temp_data/census-acs-acs5-2023-region15-b01001.schema.yaml.
2026-05-12 11:00:17,327 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001.define_schema: Defining schema for acs/acs5 / 2023 / B01001.
2026-05-12 11:00:18,572 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001.save: Writing resource to temp_data/census-acs-acs5-2023-region15-b01001.resource.yaml.
2026-05-12 11:00:18,613 | INFO | morpc_census.api.CensusAPI.census-acs-acs5-2023-region15-b01001.save: Save complete and resource validated.
filename: census-acs-acs5-2023-region15-b01001.long.csv
exists:   True

In [24]:
from frictionless import Resource

Resource(f'temp_data/{b01001.name}.resource.yaml')

{'name': 'census-acs-acs5-2023-region15-b01001',
 'type': 'table',
 'title': '2023 Sex by Age for region15',
 'description': 'Census API data for B01001: Sex by Age from acs/acs5 2023 for '
                'region15.',
 'sources': [{'title': 'US Census Bureau API',
              'path': 'https://api.census.gov/data/2023/acs/acs5?',
              '_params': {'get': 'group(B01001)',
                          'for': 'county:041,045,049,089,097,129,159,083,101,117,047,073,091,127,141',
                          'in': 'state:39'}}],
 'path': 'census-acs-acs5-2023-region15-b01001.long.csv',
 'scheme': 'file',
 'format': 'csv',
 'mediatype': 'text/csv',
 'schema': 'census-acs-acs5-2023-region15-b01001.schema.yaml'}

In [25]:
from frictionless import Schema

Schema(f'temp_data/{b01001.name}.schema.yaml')

{'fields': [{'name': 'geoidfq',
             'type': 'string',
             'description': 'Census geography fully-qualified identifier'},
            {'name': 'name', 'type': 'string', 'description': 'Geography name'},
            {'name': 'reference_period',
             'type': 'integer',
             'description': 'Reference year'},
            {'name': 'survey',
             'type': 'string',
             'description': 'Census survey endpoint'},
            {'name': 'concept',
             'type': 'string',
             'description': 'Table concept description'},
            {'name': 'universe',
             'type': 'string',
             'description': 'Universe for the table'},
            {'name': 'variable_label',
             'type': 'string',
             'description': 'Human-readable variable label'},
            {'name': 'variable',
             'type': 'string',
             'description': 'Base variable code'},
            {'name': 'estimate',
             'type': 'number',
             'description': 'Estimate value for the variable'},
            {'name': 'moe',
             'type': 'number',
             'description': 'Margin of error for the estimate'}],
 'missingValues': ['',
                   '-222222222',
                   '-333333333',
                   '-555555555',
                   '-666666666',
                   '-888888888',
                   '-999999999',
                   '*****'],
 'primaryKey': ['geoidfq', 'reference_period', 'variable']}